spring:
  application:
    name: client-service
#  cache:
#    redis:
#      time-to-live: 60000
#    type: redis
#    host: 127.0.0.1
#    port: 6379
server:
  port: 8080

grpc:
  server:
    port: 9090
    enable-reflection: true
